### ISSUE TITLE
Bug on writing comments with android phones

### ISSUE THREAD

**Issue by Arashfa0301** [webkom/lego#3029] opened 2022-10-26 09:08 UTC
A bug occurs when writing in a comment with android phones where a default string value shows up in the comment field. So by writing "hey", the value in the field becomes "kommentarhey".
![312631206_1140022703316894_9038295814231679639_n](https://user-images.githubusercontent.com/90712892/197985538-0341e8dc-834d-4584-b976-23d23e879dfb.jpg)

**Comment by LudvigHz** [comment] 2022-10-26 09:14
Sort of duplicate of #1383.

The upstream issue is https://github.com/webkom/lego-editor/issues/293, which was marked as closed with the last release but quickly discovered did not fix all issues.

**Comment by LudvigHz** [comment] 2022-10-26 09:24
@Arashfa0301 Could you also see if you experience the same issues here: https://www.slatejs.org/examples/richtext?

**Comment by ivarnakken** [comment] 2022-10-26 23:52
Closing, due to being a duplicate. Comments are generally a very buggy part of our webapp.

**Closed by ivarnakken** 2022-10-26 23:52 UTC
Labels: bug
