### ISSUE TITLE
Overflowing text on the page 'Info om Abakus'

### ISSUE THREAD

**Issue by haukkagu** [webkom/lego#3210] opened 2023-02-08 13:34 UTC
Self-explanatory from the picture below. Guessing this was introduced when the font was changed to Inter?

![image](https://user-images.githubusercontent.com/66320400/217544286-039adf7e-3045-4d39-9ad9-56f4ed7c639a.png)

**Comment by ivarnakken** [comment] 2023-02-08 13:35
Related linear issue: ABA-250

**Comment by shyamtawli** [comment] 2023-02-08 13:55
Hey can I work on this?

**Comment by ivarnakken** [comment] 2023-02-08 16:31
@shyamtawli
Yes you can 😄

**Comment by shyamtawli** [comment] 2023-02-09 06:44
@ivarnakken can you help in finding the source file and please send the link where the issue is coming.

**Comment by jonasdeluna** [comment] 2023-02-13 10:43
@shyamtawli Hi, it's in the web-app repository. You can find it here: https://github.com/webkom/lego-webapp

**Comment by ivarnakken** [comment] 2023-02-18 12:36
Resolved in https://github.com/webkom/lego-webapp/pull/3588

**Closed by ivarnakken** 2023-02-18 12:36 UTC
Labels: frontend, small-fix, good-first-issue
