### ISSUE TITLE
Registering interest and getting followers of event fails

### ISSUE THREAD

**Issue by estensen** [webkom/lego#1495] opened 2019-03-14 12:13 UTC
When I load [this](https://abakus.no/events/2392) event I get an error saying "Henting av hendle følgere feilet". Trying to register it as a favorite I get the error "Registrering av interesse feilet"

![Screenshot 2019-03-14 13 11 38](https://user-images.githubusercontent.com/9142800/54355929-aa51cf80-465a-11e9-9e98-2bc2223a87f8.png)

**Comment by orhanhenrik** [comment] 2019-03-14 14:22
Duplicate of #1481 #1482

**Closed by orhanhenrik** 2019-03-14 14:22 UTC
