### ISSUE TITLE
Visual indicator when unregister is punished

### ISSUE THREAD

**Issue by kristianvld** [webkom/lego#2719] opened 2022-05-11 11:02 UTC
Suggestion to add some visual indicator to notify users that unregistering from an event will lead to getting a "prikk".

![image](https://user-images.githubusercontent.com/7207116/167834454-5dd4a50b-b8fc-4aae-9862-b78e126480b7.png)

E.g. a warning symbol with hover text, or just some text below the button.

**Comment by SmithPeder** [comment] 2022-05-11 11:08
The modal will tell you that unregistering will lead to getting a penalty.

I feel like this is enough? I'm kinda against cluttering the sidebar even more 🙃 

![image](https://user-images.githubusercontent.com/23152018/167835572-f0580d67-17c8-4fe2-a9de-431c1993dff6.png)

**Comment by kristianvld** [comment] 2022-05-11 13:06
Hm, I did not get that modal when trying to unregister from [1] yesterday. Maybe it was just that the whole event was buggy, as i was put on waiting list even though there were places still left. When trying to unregister and re-register, I got a "prikk" without any indication. Only got an e-mail notification. 

[1] https://abakus.no/events/3122

**Comment by kristianvld** [comment] 2022-05-11 13:07
Also, what is the differ

**Comment by kristianvld** [comment] 2022-05-11 13:08
Also, what is the difference between `Avregistrering stenger` and `Avregistreringsfrist`

![image](https://user-images.githubusercontent.com/7207116/167857335-e43bb07a-f04e-4cd0-b02f-0fcd1a1f4fac.png)

**Comment by LudvigHz** [comment] 2022-05-12 09:31
> Hm, I did not get that modal when trying to unregister from [1] yesterday

Hmm, that should not happen. Did the modal not show at all, or did you not get the same content as the screenshot?
Also, could you give some details about OS/browser version?

> i was put on waiting list even though there were places still left.

This was most likely due to the server issues we were having yesterday, causing the "rebalancing" not to happen. (The task that checks whether there is space in the event and moves you up from the waiting list). So this is "expected".

> Also, what is the difference between Avregistrering stenger and Avregistreringsfrist

"Avregistreringsfrist" is the deadline for getting a penalty and "Avregistrering stenger" is a hard deadline (essentially meaning you'll get two penalties for not showing up).

It's horribly worded and confusing, and we have a fix coming soon that will hopefully make the whole thing alot clearer (https://github.com/webkom/lego-webapp/pull/2682)

**Comment by kristianvld** [comment] 2022-05-12 09:52
I did not get any modal at all. I tried unregister, and when I was going to press the register button again, I could not due to the penalty and I had to wait, along with a countdown until I could register again.

NixOS / Firefox 96.0.3, with uBlock and some other extensions, but don't think they interfere too much.

If something were to block the modal from showing, then I suppose it should have acted as if I canceled the action instead of confirming?

I suppose it could also be the case that my browser was out of sync, if for instance the unregister date had been moved, my browser had not seen that information client side, so it sends the request to unregister, server side it sees it is past the deadline and when you unregister it applies the penalty. Or is there maybe some edge case when the open registration date and the penalty date is equal?

I did open freshly navigate to abakus.no and the event just a little while before submitting the unregister, so seems strange if the unregister date should have been updated in the few minutes that happened.

**Comment by LudvigHz** [comment] 2022-05-12 10:22
Hmm. I'm very sure that there is no possible way to have button say "unregister" and the modal not showing, since it's the same value determining the type of the request and the modal, so those cannot be out of sync. I.e. the modal will show whenever you unregister, regardless if you get penalties or not.

So either you managed to click the button in the millisecond between react updates, or there was a weird bug in react.

However, with the fact that you say you were in the waiting list, you might be right that your browser was out of sync. Or that you were moved into the event right after you submitted the unregistration request, as you should definitely not get a penalty for unregistering when you are on the waiting list.

I think most of this was just due to the server issues, as that might explain the inconsistency with the waiting list and penalties.

I think we can close this as we can't reproduce this, and I can't find a reason for the modal and submission type (unregister/register) to be out of sync. Also, a lot of factors played into this specific issue (wrong event configuration and server issues). Hopefully we won't ever see this again :crossed_fingers:.

**Closed by LudvigHz** 2022-05-12 10:22 UTC
